### ISSUE TITLE
SameSite=None warning from Chrome DevTools console

### ISSUE THREAD

**Issue by naoyanickf** [newrelic/rpm#320]
As of today（02/14/2020）, I got a warning with latest version（6.8.0.360）

```
A cookie associated with a cross-site resource at https://nr-data.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

How can I clear this warning?

**Comment by mwlang** [comment]
@naoyanickf I am researching this and will get back to you when I have some more info.  Meanwhile, I did find an article on recent changes to how Chrome handles cookies:  https://www.theregister.co.uk/2020/01/30/google_chrome_80_cookies/

**Comment by mwlang** [comment]
We are internally aware of this issue and working towards resolving across the board.  It is definitely due to default behavior of the Chrome browser changing in how cookies are handled and the UI teams are working diligently towards resolution across the board.  

For further reference and discussion, you may be interested in this forum thread:  https://discuss.newrelic.com/t/chrome-warning-for-cookie-samesite-attribute/84976/43

Since this is not directly in the Ruby Agent code, I am closing this issue with this comment.  If you have questions or concerns, please reach out to our support team.

**Comment by naoyanickf** [comment]
@mwlang Thank you so much! I got it!
