### ISSUE TITLE
Error in grape instrumentation

### ISSUE THREAD

**Issue by fidalgo** [newrelic/rpm#328]
```
17 Mar 2020 00:00:00.293182 <190>1 2020-03-16T23:59:59.903998+00:00 app web.6 - - ** [NewRelic][2020-03-16 23:59:59 +0000 web.6 (4)] WARN : Error in Grape instrumentation
17 Mar 2020 00:00:00.293205 <190>1 2020-03-16T23:59:59.904097+00:00 app web.6 - - ** [NewRelic][2020-03-16 23:59:59 +0000 web.6 (4)] WARN : NoMethodError: undefined method `[]' for nil:NilClass
```

I'm seeing a lot of this errors, and since they are from NewRelic I don't know how to properly address them
Leaving here the Gemfile lock because of the versions.

[Gemfile.lock.txt](https://github.com/newrelic/rpm/files/4343878/Gemfile.lock.txt)

 since they are not reported.

**Comment by tannalynn** [comment]
Hello @fidalgo !
So, we don’t officially support Grape 1.3.0 in the agent yet, but from our testing we believe it should be working for you. What you’re seeing doesn’t appear to be an issue with the agent, it’s saying that it can’t instrument specific grape calls. This is likely because env is nil when it gets here https://github.com/newrelic/rpm/blob/29bc3e0bf6f4d11b21ced7fc38916b9e41f3a680/lib/new_relic/agent/instrumentation/grape.rb#L128-L129 
So the next step would be to investigate in your code why env would be nil in this case.

**Comment by mwlang** [comment]
@fidalgo I think your issue may be related to recent changes in Rack.  please try setting your rack version to < 2.1.0 in your Gemfile like so:
```
gem 'rack', '< 2.1.0'
``` 
This is a known issue with Grape.  I think the latest versions of Grape and Rack fixes, but it's currently untested by us.  We do know Grape 1.3.0 works with older versions of Rack, hence the recommendation above to try first.

I am closing this issue with this comment, but if you find it doesn't resolve your issue, please reopen or escalate through our support channel where we can collect more information about your specific versions and environment to diagnose further.

**Comment by magni-** [comment]
> So, we don’t officially support Grape 1.3.0 in the agent yet

Is Grape 1.3 (or 1.4) support planned?
