### ISSUE TITLE
NoMethodError sometimes raised from PrioritySampledBuffer after calling NewRelic::Agent.record_custom_event

### ISSUE THREAD

**Issue by bak1an** [newrelic/rpm#343]
Here is the full trace from newrelic_rpm gem:

```
undefined method `fix' for #<Array:0x0000559dd9c9bf68>
Did you mean?  find
<GEM_HOME>/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/priority_sampled_buffer.rb:36:in `append'
<GEM_HOME>/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/custom_event_aggregator.rb:38:in `block in record'
<GEM_HOME>/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/custom_event_aggregator.rb:37:in `synchronize'
<GEM_HOME>/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/custom_event_aggregator.rb:37:in `record'
<GEM_HOME>/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent.rb:327:in `record_custom_event'
...
<GEM_HOME>/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
...
```

It does not happen often, we are getting this maybe 3-4 times a day, sometimes in production (which is doing 50M+ transactions per day), sometimes in CI while running the tests (tests run with `monitor_mode: false`).

It is a nasty error as it crashes the transaction, few times we saw it while processing client payments, so this looks rather critical.

We don't have any specific steps or `record_custom_event` params to reproduce the issue, it affects various transactions seemingly at random.

Digging into the logs we were able to find those errors with `newrelic_rpm-6.7.0.359` and `newrelic_rpm-6.10.0.364` versions as well.

**Comment by tannalynn** [comment]
Hello @bak1an!
Thank you for bringing this issue to our attention.
I saw that you also opened a ticket with support which is great! We'll communicate through the support ticket to gather more information and investigate the issue. 
thank you!

**Comment by mwlang** [comment]
This is resolved and was a bug in how we start sampling items in the priority sampling buffer.  As noted, it’s a rare and a hard to reproduce scenario, but the flaw in the original implementation was noted and repaired to prevent this occurring.  

There are two ways to mitigate until this fix is available in the next release of the agent.

1. To lower the potential frequency of the bug encountered,  you could try increasing https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration#custom_insights_events-max_samples_stored - which has the effect of reaching the buffer capacity less quickly, but also increases memory usage since more data is retained. This setting defaults 1000 events but can be safely increased up to 10,000.

2. Below is a patch that fixes the flawed logic and could be loaded with the Rails initializer or after the Ruby agent gem is loaded:

```Ruby
module NewRelic
  module Agent
    class PrioritySampledBuffer < EventBuffer

      def heapify_items_array
        if @items.is_a?(Array)
          @items = Heap.new(@items) { |x| priority_for(x) } 
        end
      end

      # expects priority and a block, or an event as a hash with a `priority` key.
      def append(priority: nil, event: nil, &blk)
        increment_seen

        return if @capacity == 0

        if full?
          priority ||= priority_for(event)
          if priority_for(@items[0]) < priority
            heapify_items_array
            incoming = event || blk.call
            @items[0] = incoming
            @items.fix(0)
            incoming
          else
            nil
          end
        else
          @items << (event || blk.call)
          @captured_lifetime += 1
          @items[-1]
        end
      end
    end
  end
end
```

**Comment by bak1an** [comment]
Thanks @mwlang !
